# Site settings
title: This is probably not the site you are looking for!
description: > # this means to ignore newlines until "baseurl:"
  You attempted to reach stribika.github.io, but instead you actually reached a
  server identifying itself as a shape shifter humanoid reptile alien. This may
  be caused by a misconfiguration on the server or something more serious. An
  attacker on your network could be trying to get you to visit a fake (and
  definitely harmful) version of stribika.github.io. You should not proceed.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stribika.github.io" # the base hostname & protocol for your site
twitter_username: stribika
github_username:  stribika

# Build settings
markdown: kramdown
